# Generated by Django 5.0.6 on 2026-07-11 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("LEGS", "Legs"),
                            ("SHOULDERS", "Shoulders"),
                            ("ARMS", "Arms"),
                            ("CORE", "Core"),
                            ("FULL_BODY", "Full Body"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("DUMBBELL", "Dumbbell"),
                            ("BARBELL", "Barbell"),
                            ("MACHINE", "Machine"),
                            ("RESISTANCE_BAND", "Resistance Band"),
                            ("KETTLEBELL", "Kettlebell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField()),
                ("instructions", models.TextField()),
                ("risk_factors", models.JSONField(blank=True, default=list)),
                (
                    "safe_alternative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exercises.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
