# Generated by Django 5.0.6 on 2026-07-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.FloatField()),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        max_length=15,
                    ),
                ),
                ("has_lumbar_pain", models.BooleanField(default=False)),
                ("has_hernia", models.BooleanField(default=False)),
                ("disabilities", models.JSONField(blank=True, default=list)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("LOSE_WEIGHT", "Lose Weight"),
                            ("GAIN_MUSCLE", "Gain Muscle"),
                            ("GENERAL_FITNESS", "General Fitness"),
                            ("MOBILITY", "Mobility"),
                        ],
                        default="GENERAL_FITNESS",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
